# Generated by Django 4.2.14 on 2024-07-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishment',
            old_name='title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='accomplishment',
            old_name='description',
            new_name='content',
        ),
    ]
